import { useState } from "react";

import Head from "next/head";

import Container from "@mui/material/Container";
import Grid from "@mui/material/Grid";

import Navbar from "../components/Navbar";
import PopularAuthors from "../components/PopularAuthors";
import AuthorInfo from "../components/AuthorInfo";

export default function Home() {
  const [authorKey, setAuthorKey] = useState("OL23919A");
  return (
    <div>
      <Head>
        <title>Library App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar
        getAuthorKey={(event) => {
          setAuthorKey(event);
        }}
      />
      <main>
        <Container maxWidth="md">
          <Grid container spacing={4}>
            <Grid item xs={8}>
              <AuthorInfo authorKey={authorKey} />
            </Grid>
            <Grid item xs={4}>
              <PopularAuthors
                authorKey={authorKey}
                getAuthorKey={(event) => {
                  setAuthorKey(event);
                }}
              />
            </Grid>
          </Grid>
        </Container>
      </main>
    </div>
  );
}
